### PR TITLE
Update to V6 almost latest

### PR DESCRIPTION
**Pull request by danielmarbach**
This lifts CastleWindsor to the latest unstable.

All container tests are now passing.

@Particular/container-maintainers what do we do with the acceptance tests? I ditched the normal ATTs here. I think we should just have a few custom made ATTs on top of the ATT lib in each container repo. What's your thought?

### CODE REVIEW

**Comment by HEskandari** [comment]
@danielmarbach isn't running the existing ATTs with the container at hand enough? What would be the benefit of running custom ATTs?

**Comment by danielmarbach** [comment]
@HEskandari discussed this with @Particular/nservicebus-maintainers and we came to the conclusion that running all ATTs defined by the core is overkill. Much better would be to have a few ATTs which use the container directly and show the different supported scenarios.

**Comment by danielmarbach** [comment]
@WilliamBZA can you review and merge?

**Comment by WilliamBZA** [comment]
Difficult to see anything because of the volume of changes :(

Merging on the assumption that the acceptance tests and container tests passing are enough :/

**Pull request merged**
